services:
  - type: web
    name: sgg-n8n
    env: docker
    repo: https://github.com/alexmam80/n8n-render
    branch: main
    autoDeploy: true
    
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1

    envVars:
      - key: N8N_HOST
        value: sgg-n8n-render.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: TZ
        value: Europe/Chisinau
      - key: DB_SQLITE_POOL_SIZE
        value: 5
      - key: N8N_RUNNERS_ENABLED
        value: 'true'
      - key: N8N_BLOCK_ENV_ACCESS_IN_NODE
        value: 'false'
      - key: N8N_GIT_NODE_DISABLE_BARE_REPOS
        value: 'true'
      - key: N8N_BASIC_AUTH_ACTIVE
        value: 'true'
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Tineretei60!
      - key: N8N_EDITOR_BASE_URL
        value: https://sgg-n8n-render.onrender.com/
